[package]
name = "fetchrs"
version = "0.1.0"
authors = ["Michael Wilson <wilsoniya@gmail.com>"]

[dependencies]
futures = "0.1.23"
hyper = "0.12.7"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
